export const projects = [
  {
    name: "iMaski",
    description: "A pet care platform connecting owners with local vets.",
    img: "/work-projects/desktop/timaski.png",
    mobileImg: "/work-projects/mobile/timaski.png",
    route: "/sample-project",
  },
  {
    name: "Connect2Pet",
    description: "Reimagining the pet adoption experience with fun and accessibility.",
    img: "/work-projects/desktop/connect2pet.png",
    mobileImg: "/work-projects/mobile/connect2pet.png",
    route: "/sample-project",
  },
  {
    name: "GeoDIQA",
    description: "AI-powered document analysis for geoscience workflows.",
    img: "/work-projects/desktop/geodiqa.png",
    mobileImg: "/work-projects/mobile/geodiqa.png",
    route: "/sample-project",
  },
  {
    name: "Foldly",
    description: "One platform, endless file collection possibilities.",
    img: "/work-projects/desktop/foldly.png",
    mobileImg: "/work-projects/mobile/foldly.png",
    route: "/sample-project",
  },
  {
    name: "Arlenis Designs",
    description: "Elegant interior design showcase with immersive visuals.",
    img: "/work-projects/desktop/arlenis-designs.png",
    mobileImg: "/work-projects/mobile/arlenis-designs.png",
    route: "/sample-project",
  },
  {
    name: "Gunny",
    description: "Bold gaming identity with a fierce visual presence.",
    img: "/work-projects/desktop/gunny.png",
    mobileImg: "/work-projects/mobile/gunny.png",
    route: "/sample-project",
  },
  {
    name: "$CRAZY",
    description: "A meme token project with playful branding and community focus.",
    img: "/work-projects/desktop/crazy-token.png",
    mobileImg: "/work-projects/mobile/crazy-token.png",
    route: "/sample-project",
  },
  {
    name: "Stay Maxxed",
    description: "Trading platform interface with bold, confident aesthetics.",
    img: "/work-projects/desktop/stay-maxxed.png",
    mobileImg: "/work-projects/mobile/stay-maxxed.png",
    route: "/sample-project",
  },
  {
    name: "Crazy Clips",
    description: "Video content platform with sleek dark-themed design.",
    img: "/work-projects/desktop/crazy-clips.png",
    mobileImg: "/work-projects/mobile/crazy-clips.png",
    route: "/sample-project",
  },
  {
    name: "Tiger Fart",
    description: "Humorous meme project with striking visual identity.",
    img: "/work-projects/desktop/tiger-fart.png",
    mobileImg: "/work-projects/mobile/tiger-fart.png",
    route: "/sample-project",
  },
  {
    name: "Rainbow Loader",
    description: "Creative loading experience with vibrant animations.",
    img: "/work-projects/desktop/rainbow-loader.png",
    mobileImg: "/work-projects/mobile/rainbow-loader.png",
    route: "/sample-project",
  },
  {
    name: "iMaski Loader",
    description: "Sleek preloader design for the iMaski platform.",
    img: "/work-projects/desktop/timaski.png",
    mobileImg: "/work-projects/mobile/timaski.png",
    route: "/sample-project",
  },
];
